### Get all resources
GET http://localhost:3001/api/persons

### Get a particular resource my means of its id.
GET http://localhost:3001/api/persons/3

### To test deleting a particular phonebook entry
DELETE http://localhost:3001/api/persons/1

### For testing adding new phonebook entries
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Maria Poppendieck", 
    "number": "49-33-6233122"
}