### Get all resources
GET http://localhost:3001/api/persons

### Get a particular resource my means of its id.
GET http://localhost:3001/api/persons/someInvalidId

### Get a particular resource my means of its id.
GET http://localhost:3001/api/persons/628be823e8de4cdad6e0720a

### To test deleting a particular phonebook entry
DELETE http://localhost:3001/api/persons/628be95bead5a90323f6bc3f

### For testing adding new phonebook entries
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Maria Poppendieck", 
    "number": "49-33-6233122"
}

### Test duplicate name
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "49-33-6233122"
}

### Test duplicate name containing different letter cases
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "arto Hellas",
    "number": "49-33-6233122"
}

### Add new entry
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Kaiju Altonen",
    "number": "49-33-6233122"
}

### test name missing in post operation
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Li",
    "number": "49-33-6233122"
}

### Test number missing in post operation
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas"
}

### Add new entry
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Markus Brown",
    "number": "040-243563"
}

### Modify entry
PUT http://localhost:3001/api/persons/628be823e8de4cdad6e0720a
Content-Type: application/json

{
    "name": "Liisa Marttinen",
    "number": "044-3991003"
}
